### ISSUE TITLE
Pyhton 2.7

### ISSUE THREAD

**Issue by PaprikaX33** [PaprikaX33/stupidly-simple-calculator#5]
We are doing python 2.7?
Not python 3??

**Comment by roidsaja** [comment]
python 2.7 is dying , so experience that last moment with ver 2.7 :)

**Comment by roidsaja** [comment]
There's a reddit forum from 2 years ago on why people still use Python ver 2.7. Safe to say it's just easier to implement :+1: 
[link to reddit](https://www.reddit.com/r/Python/comments/5kltzn/why_people_still_use_python_27/)
